spring.application.name=GestionFinanzas
spring.datasource.url=jdbc:postgresql://localhost:5432/Gestion_Finanzas
spring.datasource.username=JoseGG8
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true