spring.application.name=GestionFinanzas

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:Gestion_Finanzas}${DB_JDBC_SUFFIX:?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:JoseGG8}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:admin}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}



# Render inyecta PORT automáticamente
server.port=${PORT:8080}
